# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a3f8d6bd858821f11998fd6ea48fb879a41b0c084c63066f6e2fc3903c907e3715c825c1624a1c9bbb71d98a634b9769b24c8a76e75c5f5a956542d0397a59b0

test:
  secret_key_base: 0581b61802d99e6c68ab0298669da77cbcd383bc33388e3735797bb9c27acdb8f6064e5dfd06a0eda2688d9582af9bc11774c420a5c807167ff36883aeeb7018

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
